### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by jcvdav** [FishyLab/MPAs_R_Fun#5]
@jsausville  , for your paper you'll have the following figures:

- Fig1 - map
- Fig2:
    - a - c vs m with colors for R
    - b - c vs m with colors for N
- Fig3 - N through time for management recommendation

**Comment by jsausville** [comment]
Hey @jcvdav,  if it's doable/convenient could you take a look at my figure 1.html to see if my maps are good to go?

**Comment by jsausville** [comment]
Here is the rawgit Link: https://rawgit.com/FishyLab/MPAs_R_Fun/master/docs/fig_1_final.html

**Comment by jcvdav** [comment]
Nice use of the issues @jsausville !

I think they look good. I would just change the `scale_x_continuous(breaks = c(numbers here))` so that you have less breaks and the numbers are more spaced out. You cna see how @alishanaidu did it [here, in the second-to-last chunk of her methods section](https://rawgit.com/FishyLab/LionfishHabitat/master/docs/HabitatUtilization.html#methods)

Also, always capitalize your axis ("Latitude", "Longitude").

Other than that, LGMT 👍
